markdown: kramdown

encoding: "utf-8"

sass:
  sass_dir: css
  style: compressed

widgets:

- name: xmrr
  thumbnail: images/xmr_chart.png
  url: https://github.com/Zanidean/xmrr
  ghuser: Duc Nguyen
  ghrepo: xmrr
  tags: đồ thị cột, Control Charts, QC, XBar
  ghauthor: Duc Nguyen
  short: >
    Use xmr() for XmR data which re-calculates to signal true change, and use xmr_chart() for XmR style control charts with recalculated process limits.

- name: gg3D
  thumbnail: images/gg3D.png
  url: https://github.com/AckerDWM/gg3D
  tags: đồ thị cột, 3D, Visualization
  ghauthor: Daniel Acker
  short: >
    gg3D adds 3D axes, 3D perspective projections with arbitrary rotations, and 3D wireframe plots to ggplot.

- name: ggQC
  thumbnail: images/ggQC.png
  url: https://github.com/kenithgrey/ggQC
  ghuser: kenithgrey
  ghrepo: ggQC
  tags: đồ thị cột, QC, XmR, XbarR, SixSigma, Visualization
  ghauthor: Kenith Grey
  short: >
    ggQC is used to create single, faceted, or multi-layered quality control charts

