markdown: kramdown

encoding: "utf-8"

sass:
  sass_dir: css
  style: compressed

widgets:
  -
    name: Đồ thị cột, tô màu theo điều kiện
    url: https://www.tuhocr.com/blog/huong-dan-ve-do-thi-cot-to-mau-theo-dieu-kien
    thumbnail: images/p1.png    
    author: Bruceshark
    tags: ggplot2, barchart
    cran: true
    short: >
      Hướng dẫn vẽ đồ thị cột, tô màu theo điều kiện.
  -
    name: recogito
    thumbnail: images/p1.png  
    ghauthor: yonicd
    tags: Text annotation, Image annotation
    cran: true
    short: >
      Annotate text and images with your own labels
  
